### ISSUE TITLE
test does not work 

### ISSUE THREAD

**Issue by dy** [glslify/glsl-tokenizer#9]
Hi!
I’ve cloned and made npm install, but running tests fails with 2 errors:

``` sh
  glsl-tokenizer: invalid characters
    √ does not hang!
    √ collects all expected "operator" characters

  tests 5
  pass  3
  fail  2

  Failed Tests: There were 2 failures

    × glsl-tokenizer/string matches exactly the expected output
    × glsl-tokenizer/stream matches exactly the expected output

npm ERR! Test failed.  See above for more details.
```

Is that ok? json-diff shows at about a hundred diffs for that matter, so seems that fixture is old or something.

**Comment by mattdesl** [comment]
It seems pretty odd. What node/npm version? I just tested again with a fresh install on 2.1.0 and all tests are passing for me.

**Comment by mattdesl** [comment]
btw – I'm on node@5 and npm@2.14.12

**Comment by dfcreative** [comment]
npm@3.7.2, node@5.5.0, win7.
Wonder where the issue is - in the environment or in tokenizer itself

**Comment by dfcreative** [comment]
in some reason glslify returns source code with double newlines `\n\n` in place of single newlines `\n`

**Comment by dy** [comment]
Fixed.
